# версия  docker-compose
version: '3.8'

# имена и описания контейнеров, которые должны быть развёрнуты
services:
  # описание контейнера db
  db:
    # образ, из которого должен быть запущен контейнер
    image: postgres:12.4
    # volume и связанная с ним директория в контейнере
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data/
    # адрес файла, где хранятся переменные окружения
    env_file:
      - .env
    # Условия по которым мы определяем что в контейнере поднялась БД
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      timeout: 10s
      interval: 1s
      retries: 10

  web:
    depends_on:
      db:
        condition: service_healthy

    image: markoffdev/yatube:latest
    restart: always
    volumes:
      - ./data/static:/code/static/
      - ./data/media:/code/media/
      - ./logs:/code/logs/
    env_file:
      - .env

  nginx:
    image: nginx:1.19.6
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/www/logs/
      - ./data/static:/var/www/static/
      - ./data/media:/var/www/media/
    depends_on:
      - web